name: example
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_image_editor:
    path: ../
    
  intl: ^0.20.1
  
  bot_toast: ^4.1.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.1
  gal: ^2.3.2
  google_fonts: ^6.3.0
  file_saver: ^0.3.1
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  http: ^1.4.0
  supabase_flutter: ^2.9.1
  image_background_remover: ^1.0.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  flutter_colorpicker: ^1.1.0
  vibration: ^3.1.1

  # Video-Editing
  pro_video_editor: ^0.2.3
  ### Choose one player below
  video_player: ^2.10.0
  chewie: ^1.12.1
  flick_video_player: ^0.9.0
  media_kit: ^1.2.0 # Primary package.
  media_kit_video: ^1.3.0 # For video rendering.
  media_kit_libs_video: ^1.0.6 # Native video dependencies.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo.png
    - assets/demo.mp4
    - assets/frame.png
    - assets/frame1.png
    - assets/google_fonts/