name: pro_image_editor
description: "A Flutter image editor: Seamlessly enhance your images with user-friendly editing features."
version: 11.14.0
homepage: https://github.com/hm21/pro_image_editor/
repository: https://github.com/hm21/pro_image_editor/
documentation: https://github.com/hm21/pro_image_editor/
funding:
  - https://github.com/sponsors/hm21

topics:
  - image-editor
  - image
  - photo
  - picture
  - editor

screenshots:
  - description: "Showcase from the image editor with the frosted-glass design"
    path: assets/showcase-frosted-glass.jpg
  - description: "Showcase from the image editor with the WhatsApp design"
    path: assets/showcase-whatsapp.jpg
  - description: "Showcase from the image editor with simple design"
    path: assets/showcase.jpg

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  plugin_platform_interface: ^2.1.8
  shared_preferences: ^2.5.3
  vector_math: ^2.1.4
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.8.0
  flutter_lints: ^6.0.0
  import_sorter: ^4.6.0
  mockito: ^5.5.1
  network_image_mock: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: ch.waio.pro_image_editor
        pluginClass: ProImageEditorPlugin
  assets:
    - lib/web/web_worker.dart.js
    - lib/web/web_worker.dart.js.map
  shaders:
    - lib/shared/shaders/pixelate.frag
  fonts:
   - family: ProImageEditorIcons
     fonts:
      - asset: assets/fonts/ProImageEditorIcons.ttf